# -*- coding: utf-8 -*-
"""Data_Scraper_Slate.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1FOXQjv9W998F41W8hkDrtAFFMElNsFMQ
"""

! pip install newscatcherapi
from newscatcherapi import NewsCatcherApiClient
import csv
import time
import os.path
import shutil

from google.colab import drive
drive.mount('/content/gdrive')

# Commented out IPython magic to ensure Python compatibility.
# %cd /content/gdrive/MyDrive/Slate Summary

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='Biden',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Biden.txt", 'a'))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='Trump',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Trump.txt", "a"))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='pandemic',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Pandemic.txt", "a"))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='vaccine',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Vaccine.txt", "a"))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='Ukraine',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Ukraine.txt", "a"))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='Protest',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Protest.txt", "a"))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='Democrat',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Democrat.txt", "a"))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='Inflation',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Inflation.txt", "a"))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='Republican',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Republican.txt", "a"))
    time.sleep(0.33)

newscatcherapi = NewsCatcherApiClient(x_api_key='EcTsDEjSjLEk46mk6G9XBcFWXKVIBBHi2Lfocq7IYs4')

all_articles = newscatcherapi.get_search(q='Election',
                                         lang='en',
                                         sources= "slate.com",
                                         page_size=10)

count = 0
articles = all_articles['articles']
for article in articles[:10]:   
    count+=1
    print(str(count) + ". " 
    + "\n\t\t" + article["summary"]\
    + "\n\n",
    file=open("Slate_Election.txt", "a"))
    time.sleep(0.33)